description = "Tag Storage Accounts in accordance with XXXX policy"
discussion = "To provide Security Operations the ability in the case of an security incident to understand the classification of the data that maybe impacted"
id = "SA-AM_6_SA_0015"
name = "AM-6_SA_0015"

[tags]
CSP = "Azure"
Service = "StorageAccounts"
Control_Owner = "SIA"
SCF_Sub_Objective = "000-000-00-00"
Defined_In_MCSB = false
Resource_Configuration = true
NIST80053_Control_Families = [ "Configuration Management",]
NIST80053_Control_Ids = [ "CM-1",]
References = []


[tools]
[tools.azurepolicy]
Builtin_Policy = "N/A"
Default_Effect = "N/A"
Required_Effect = "Audit"
Possible_Implementation = true