description = "Disable Storage Account cross tenant replication"
discussion = "Prevent the replication of Storage Account objects to a non XXXX Azure tenant"
id = "SA-DP_2_SA_0009"
name = "DP_2_SA_0009"

[tags]
CSP = "Azure"
Service = "StorageAccounts"
Control_Owner = "SIA"
SCF_Sub_Objective = "000-000-00-00"
Defined_In_MCSB = false
Resource_Configuration = true
NIST80053_Control_Families = ["Access Control"]
NIST80053_Control_Ids = ["AC-2"]
References = []


[tools]
[tools.azurepolicy]
Builtin_Policy = "/providers/Microsoft.Authorization/policyDefinitions/92a89a79-6c52-4a7e-a03f-61306fc49312"
Default_Effect = "Audit"
Required_Effect = "Deny"
Possible_Implementation = true