description = "Disable Public Network Access"
discussion = "Removes the possibility of accidental or intended public exposure of data"
id = "SA-NS_2_SA_0004"
name = "NS_2_SA_0004"

[tags]
CSP = "Azure"
Service = "StorageAccounts"
Control_Category = "Access Control"
Control_Owner = "SIA"
SCF_Sub_Objective = "000-000-00-00"
Defined_In_MCSB = true
Resource_Configuration = true
NIST80053_Control_Families = ["Access Control"]
NIST80053_Control_Ids = ["AC-2"]
References = []


[tools]
[tools.azurepolicy]
Builtin_Policy = "/providers/Microsoft.Authorization/policyDefinitions/b2982f36-99f2-4db5-8eff-283140c09693"
Default_Effect = "Audit"
Required_Effect = "Deny"
Possible_Implementation = true
