description = "Use least privilege RBAC roles for Storage Account authorisation"
discussion = "Using roles like Storage Blob Data Reader reduces the blast radius should an identity become compromised"
id = "SA-PA_7_SA_0014"
name = "PA_7_SA_0014"

[tags]
CSP = "Azure"
Service = "StorageAccounts"
Control_Owner = "SIA"
SCF_Sub_Objective = "000-000-00-00"
Defined_In_MCSB = true
Resource_Configuration = false
NIST80053_Control_Families = ["Access Control"]
NIST80053_Control_Ids = ["AC-2"]
References = []


[tools]
[tools.azurepolicy]
Builtin_Policy = "N/A"
Default_Effect = "N/A"
Required_Effect = "N/A"
Possible_Implementation = false