name = "Disable Public Network Access"
description = "Storage Accounts must enforce a network guardrail if persisting data with internal and above data classification (What) within its Network settings (How) in order to prevent data exposure to the internet (Why)"
id = "SA-010"
csp = "Azure"
service = "Microsoft.Storage/StorageAccounts"
control_owner = "Cloud"
quality_model = "Security" #

[framework."NIST80053"."Access Control"]
control_id = "AC1"
[framework."MSCSB"."Azure security baseline for Storage"]
control_id = "NS-2"

[tools.azurepolicy]
system = "Azure Policy"
reference = "/providers/Microsoft.Authorization/policyDefinitions/b2982f36-99f2-4db5-8eff-283140c09693"
default_action = "Audit"
action = "Deny" # Deny | Audit | None |
type = "Default" # Default | Custom
ttl = 48 # hours before the control or resources are timed out and deemed to not exist
is_blocking = true # should or could the control block deployment


