description = "Use System Assigned Managed Identity for CMK Key Vault access"
discussion = "A user assigned identity provides the ability for an identity to have access to multiple Storage Accounts CMK’s increasing the blast radius in the case of compromise"
id = "SA-DP_8_SA_0016"
name = "DP_8_SA_0016"

[tags]
CSP = "Azure"
Service = "StorageAccounts"
Control_Owner = "SIA"
SCF_Sub_Objective = "000-000-00-00"
Defined_In_MCSB = false
Resource_Configuration = true
NIST80053_Control_Families = ["Access Control"]
NIST80053_Control_Ids = ["AC-2"]
References = []


[tools]
[tools.azurepolicy]
Builtin_Policy = "N/A"
Default_Effect = "N/A"
Required_Effect = "Audit"
Possible_Implementation = false