description = "Disable Storage Account cross tenant replication"
discussion = "Storage Accounts must enforce the restriction of cross tenant replication (What) via its Deployment settings (How) to prevent data exfiltration (Why)"
id = "SA-SI_120"
name = "SI_120"

[tags]
CSP = "Azure"
Service = "StorageAccounts"
Control_Owner = "Landing Zone Admin Team"
SCF_Sub_Objective = "000-000-00-00"
Defined_In_MCSB = true
Should_Define_In_MSCB_Rationale = "N/A"
Technical_Configuration = true
Non_Technical_Implementation_Rationale = "N/A"
NIST80053_Control_Families = [ "System and Information Integrity",]

[tools.azurepolicy]
Builtin_Policy = "/providers/Microsoft.Authorization/policyDefinitions/92a89a79-6c52-4a7e-a03f-61306fc49312"
Default_Effect = "N/A"
Required_Effect = "Deny"
Custom_Policy_Possible = "N/A"
Not_Deny_Rationale = "N/A"
