description = "Use a CMK for encryption persisted in an HSM backed Key Vault for all Storage Account scopes"
discussion = "Storage Accounts must enforce the use of an LSEG managed encryption at rest key persisted in an HSM backed Key Vault (What) within its Encryption settings (How) in order should Microsoft's key management platform become compromised LSEG can revoke access to exfiltrated data (Why)"
id = "SA-SC_100"
name = "SC_100"

[tags]
CSP = "Azure"
Service = "StorageAccounts"
Control_Owner = "Landing Zone Admin Team"
SCF_Sub_Objective = "000-000-00-00"
Defined_In_MCSB = true
Should_Define_In_MSCB_Rationale = "N/A"
Technical_Configuration = true
Non_Technical_Implementation_Rationale = "N/A"
NIST80053_Control_Families = [ "System and Communications Protection",]

[tools.azurepolicy]
Builtin_Policy = "/providers/Microsoft.Authorization/policyDefinitions/6fac406b-40ca-413b-bf8e-0bf964659c25"
Default_Effect = "Audit"
Required_Effect = "Deny"
Custom_Policy_Possible = "N/A"
Not_Deny_Rationale = "N/A"
