description = "Enable Soft Delete for Files"
discussion = "Storage Accounts must enforce the use of File Soft Delete if files are used with a retention period of 30 days (What) within its deployment code settings (How) in order to recover data after an accidental or malicious deletion"
id = "SA-SI_150"
name = "SI_150"

[tags]
CSP = "Azure"
Service = "StorageAccounts"
Control_Owner = "Landing Zone Admin Team"
SCF_Sub_Objective = "000-000-00-00"
Defined_In_MCSB = true
Should_Define_In_MSCB_Rationale = "N/A"
Technical_Configuration = true
Non_Technical_Implementation_Rationale = "N/A"
NIST80053_Control_Families = [ "System and Information Integrity",]

[tools.azurepolicy]
Builtin_Policy = "N/A"
Default_Effect = "N/A"
Required_Effect = "Deny"
Custom_Policy_Possible = true
Not_Deny_Rationale = "N/A"
