description = "Use a minimum of TLS version 1.2 with HTTPS"
discussion = "Storage Accounts must enforce a minimum TLS version of 1.2 (What) within its Configuration settings (How) in order to use modern techniques to establish robust encrypted data channels over untrusted networks (Why)"
id = "SA-SC_090"
name = "SC_090"

[tags]
CSP = "Azure"
Service = "StorageAccounts"
Control_Owner = "Landing Zone Admin Team"
SCF_Sub_Objective = "000-000-00-00"
Defined_In_MCSB = true
Should_Define_In_MSCB_Rationale = "N/A"
Technical_Configuration = true
Non_Technical_Implementation_Rationale = "N/A"
NIST80053_Control_Families = [ "System and Communications Protection",]

[tools.azurepolicy]
Builtin_Policy = "/providers/Microsoft.Authorization/policyDefinitions/fe83a0eb-a853-422d-aac2-1bffd182c5d0"
Default_Effect = "Audit"
Required_Effect = "Deny"
Custom_Policy_Possible = "N/A"
Not_Deny_Rationale = "N/A"
