description = "Storage Accounts should have a data classification tag"
discussion = "Storage Accounts must have a data classification tag (What) via its IaC deployment code (How) in order to differentiate assets technical control requirements and to assist Security Operations in prioritising possible data breach mitigation responses (Why)"
id = "SA-SI_130"
name = "SI_130"

[tags]
CSP = "Azure"
Service = "StorageAccounts"
Control_Owner = "Landing Zone Admin Team"
SCF_Sub_Objective = "000-000-00-00"
Defined_In_MCSB = true
Should_Define_In_MSCB_Rationale = "N/A"
Technical_Configuration = true
Non_Technical_Implementation_Rationale = "N/A"
NIST80053_Control_Families = [ "System and Information Integrity",]

[tools.azurepolicy]
Builtin_Policy = "N/A"
Default_Effect = "N/A"
Required_Effect = "Deny"
Custom_Policy_Possible = true
Not_Deny_Rationale = "N/A"
