name: Automatic Merge for Version Update

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  auto_merge_version_update:
    runs-on: ubuntu-latest
    if: github.event.pull_request.author_association == 'COLLABORATOR' && contains(github.event.pull_request.labels.*.name, 'auto-version-update')
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Merge pull request
        run: |
          echo "Merging pull request #${{ github.event.pull_request.number }} created by ${{ github.event.pull_request.user.login }}"
          curl --request PUT \
          --url ${{ github.event.pull_request._links.merge.href }} \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header 'content-type: application/json' \
          --data '{
            "commit_title": "Automatically merge version update",
            "sha": "${{ github.event.pull_request.head.sha }}"
          }'
